### ISSUE TITLE
Erroring build

### ISSUE THREAD

**Issue by amoffat** [Chaosthebot/Chaos#414]
Error logs keep cycling through this

```
05-30 23:30 chaosbot     INFO     checking if I crashed before...
05-30 23:30 chaosbot     INFO     starting up and entering event loop
05-30 23:30 poll_close_stale INFO     Checking for stale issues...
05-30 23:30 github_api   DEBUG    requests remaining: inf, reset in: 0s, cooldown sleep: 0.00s
05-30 23:30 github_api   INFO     requesting GET to '/repos/chaosbot/Chaos/issues'
05-30 23:30 poll_close_stale INFO     There are currently 30 open issues
05-30 23:30 poll_close_stale INFO     Issue 413 has not been updated in 29 seconds
05-30 23:30 poll_close_stale INFO     Issue 412 has not been updated in 808 seconds
05-30 23:30 poll_close_stale INFO     Issue 411 has not been updated in 1578 seconds
05-30 23:30 poll_close_stale INFO     Issue 410 has not been updated in 268 seconds
05-30 23:30 poll_close_stale INFO     Issue 409 has not been updated in 5395 seconds
05-30 23:30 poll_close_stale INFO     Issue 408 has not been updated in 51 seconds
05-30 23:30 poll_close_stale INFO     Issue 407 has not been updated in 508 seconds
05-30 23:30 poll_close_stale INFO     Issue 406 has not been updated in 1583 seconds
05-30 23:30 poll_close_stale INFO     Issue 405 has not been updated in 1581 seconds
05-30 23:30 poll_close_stale INFO     Issue 402 has not been updated in 15329 seconds
05-30 23:30 poll_close_stale INFO     Issue 401 has not been updated in 5972 seconds
05-30 23:30 poll_close_stale INFO     Issue 400 has not been updated in 444 seconds
05-30 23:30 poll_close_stale INFO     Issue 398 has not been updated in 6481 seconds
05-30 23:30 poll_close_stale INFO     Issue 397 has not been updated in 111 seconds
05-30 23:30 poll_close_stale INFO     Issue 392 has not been updated in 1584 seconds
05-30 23:30 poll_close_stale INFO     Issue 391 has not been updated in 18896 seconds
05-30 23:30 poll_close_stale INFO     Issue 388 has not been updated in 1580 seconds
05-30 23:30 poll_close_stale INFO     Issue 387 has not been updated in 6 seconds
05-30 23:30 poll_close_stale INFO     Issue 386 has not been updated in 32794 seconds
05-30 23:30 poll_close_stale INFO     Issue 381 has not been updated in 45068 seconds
05-30 23:30 poll_close_stale INFO     Issue 374 has not been updated in 87790 seconds
05-30 23:30 poll_close_stale INFO     Issue 365 has not been updated in 93278 seconds
05-30 23:30 poll_close_stale INFO     Issue 364 has not been updated in 100104 seconds
05-30 23:30 poll_close_stale INFO     Issue 353 has not been updated in 48133 seconds
05-30 23:30 poll_close_stale INFO     Issue 345 has not been updated in 163188 seconds
05-30 23:30 poll_close_stale INFO     Issue 310 has not been updated in 35874 seconds
05-30 23:30 poll_close_stale INFO     Issue 307 has not been updated in 72025 seconds
05-30 23:30 poll_close_stale INFO     Issue 306 has not been updated in 95141 seconds
05-30 23:30 poll_close_stale INFO     Issue 291 has not been updated in 75051 seconds
05-30 23:30 poll_close_stale INFO     Issue 288 has not been updated in 59756 seconds
05-30 23:30 chaosbot     INFO     Setting description to A social coding experiment that updates its own code democratically.
05-30 23:30 github_api   DEBUG    requests remaining: 4656, reset in: 2294s, cooldown sleep: 0.01s
05-30 23:30 github_api   INFO     requesting PATCH to '/repos/chaosbot/Chaos'
05-30 23:30 schedule     INFO     Running job Every 30 seconds do <lambda>() (last run: [never], next run: 2017-05-30 23:30:55)
05-30 23:30 chaosbot     INFO     looking for PRs
05-30 23:30 chaosbot     INFO     generated meritocracy: {'rudehn', 'andrewda', 'viktorsec', 'plasmapower', 'hongaar', 'phil-r', 'amoffat', 'smittyvb', 'eukaryote31', 'rhengles'}
05-30 23:30 github_api   DEBUG    requests remaining: 4655, reset in: 2264s, cooldown sleep: 0.01s
05-30 23:30 github_api   INFO     requesting GET to '/repos/chaosbot/Chaos/pulls'
05-30 23:30 github_api   DEBUG    requests remaining: 4654, reset in: 2263s, cooldown sleep: 0.01s
05-30 23:30 github_api   INFO     requesting PUT to '/repos/chaosbot/Chaos/issues/387/labels'
05-30 23:30 chaosbot     INFO     processing PR #387
05-30 23:30 github_api   DEBUG    requests remaining: 4653, reset in: 2263s, cooldown sleep: 0.01s
05-30 23:30 github_api   INFO     requesting GET to '/repos/chaosbot/Chaos/issues/387/comments'
05-30 23:30 github_api   DEBUG    requests remaining: 4652, reset in: 2263s, cooldown sleep: 0.01s
05-30 23:30 github_api   INFO     requesting GET to '/repos/chaosbot/Chaos/issues/387/reactions'
05-30 23:30 github_api   DEBUG    requests remaining: 4651, reset in: 2263s, cooldown sleep: 0.01s
05-30 23:30 github_api   INFO     requesting GET to '/repos/chaosbot/Chaos/pulls/387/reviews'
05-30 23:30 chaosbot     INFO     PR 387 status: will be approved
05-30 23:30 github_api   DEBUG    requests remaining: 4650, reset in: 2262s, cooldown sleep: 0.01s
05-30 23:30 github_api   INFO     requesting POST to '/repos/chaosbot/Chaos/statuses/fc703c52effdae09d88937721116f23096b94dd9'
Traceback (most recent call last):
  File "chaos.py", line 116, in <module>
    main()
  File "chaos.py", line 66, in main
    schedule.run_pending()
  File "/root/.virtualenvs/chaos/lib/python3.6/site-packages/schedule/__init__.py", line 462, in run_pending
    default_scheduler.run_pending()
  File "/root/.virtualenvs/chaos/lib/python3.6/site-packages/schedule/__init__.py", line 75, in run_pending
    self._run_job(job)
  File "/root/.virtualenvs/chaos/lib/python3.6/site-packages/schedule/__init__.py", line 129, in _run_job
    ret = job.run()
  File "/root/.virtualenvs/chaos/lib/python3.6/site-packages/schedule/__init__.py", line 377, in run
    ret = self.job_func()
  File "/root/workspace/Chaos/cron/__init__.py", line 11, in <lambda>
    lambda: poll_pull_requests(api))
  File "/root/workspace/Chaos/cron/poll_pull_requests.py", line 75, in poll_pull_requests
    threshold, meritocracy_satisfied)
  File "/root/workspace/Chaos/github_api/prs.py", line 278, in post_accepted_status
    "remaining: {time}, {summary}".format(time=remaining_human, summary=votes_summary))
  File "/root/workspace/Chaos/github_api/prs.py", line 313, in post_status
    api("POST", path, json=data)
  File "/root/workspace/Chaos/github_api/__init__.py", line 93, in __call__
    resp.raise_for_status()
  File "/root/.virtualenvs/chaos/lib/python3.6/site-packages/requests/models.py", line 928, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.github.com/repos/chaosbot/Chaos/statuses/fc703c52effdae09d88937721116f23096b94dd9
```

**Comment by andrewda** [comment]
https://api.github.com/repos/chaosbot/Chaos/statuses/fc703c52effdae09d88937721116f23096b94dd9

Could it be because of the "✓" in the status descriptions?

**Comment by PlasmaPower** [comment]
@andrewda no, that's worked before. However, the `→` is new - maybe that's doing it?

**Comment by amoffat** [comment]
Also, somewhat related, should the rollback stuff have started reverting PRs?

**Comment by PlasmaPower** [comment]
Yeah, it should, but I think it might be broken or not used. Is `chaos_wrapper.sh` called anywhere?

**Comment by PlasmaPower** [comment]
It appears to be having trouble with #392, but it updated the status correctly at least once.

**Comment by PlasmaPower** [comment]
Might also be #387, not sure

**Comment by mark-i-m** [comment]
@amoffat It would not rollback if the failure happens after the first minute of runtime

**Comment by PlasmaPower** [comment]
@mark-i-m we should increase that IMO

**Comment by mark-i-m** [comment]
#418
