### ISSUE TITLE
Help! I crashed! --CB

### ISSUE THREAD

**Issue by andrewda** [Chaosthebot/Chaos#449]
Oh no! I crashed!

Failed on SHA c815cfe601ac83e16694c6d97ca7c3a465ed11b0
Rolled back to SHA 06596d92e4309ed7da6d992a328f5bff6c06a064

Error log:
```
    resp.raise_for_status()
  File "/root/.virtualenvs/chaos/lib/python3.6/site-packages/requests/models.py", line 928, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/repos/chaosbot/Chaos/issues
Crashed in less than 60 seconds!
Rollback to commit b647dd3e684390f2ee255aa1d273f2f21dcdad6d
05-31 15:12 chaosbot     INFO     checking if I crashed before...
05-31 15:12 chaosbot     INFO     it looks like I did... posting on github...
05-31 15:12 github_api   DEBUG    requests remaining: inf, reset in: 0s, cooldown sleep: 0.00s
05-31 15:12 github_api   INFO     requesting POST to '/repos/chaosbot/Chaos/issues'
Traceback (most recent call last):
  File "chaos.py", line 116, in <module>
    main()
  File "chaos.py", line 49, in main
    check_for_prev_crash(api, log)
  File "chaos.py", line 109, in check_for_prev_crash
    gh.issues.create_issue(api, settings.URN, title, body, labels)
  File "/root/workspace/Chaos/github_api/issues.py", line 60, in create_issue
    resp = api("post", path, json=data)
  File "/root/workspace/Chaos/github_api/__init__.py", line 93, in __call__
    resp.raise_for_status()
  File "/root/.virtualenvs/chaos/lib/python3.6/site-packages/requests/models.py", line 928, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/repos/chaosbot/Chaos/issues
Crashed in less than 60 seconds!
Rollback to commit c3a7a523bc14598ac44c2464f11caca42bb04680
05-31 15:12 chaosbot     INFO     checking if I crashed before...
05-31 15:12 chaosbot     INFO     it looks like I did... posting on github...
05-31 15:12 github_api   DEBUG    requests remaining: inf, reset in: 0s, cooldown sleep: 0.00s
05-31 15:12 github_api   INFO     requesting POST to '/repos/chaosbot/Chaos/issues'
Traceback (most recent call last):
  File "chaos.py", line 116, in <module>
    main()
  File "chaos.py", line 49, in main
    check_for_prev_crash(api, log)
  File "chaos.py", line 109, in check_for_prev_crash
    gh.issues.create_issue(api, settings.URN, title, body, labels)
  File "/root/workspace/Chaos/github_api/issues.py", line 60, in create_issue
    resp = api("post", path, json=data)
  File "/root/workspace/Chaos/github_api/__init__.py", line 93, in __call__
    resp.raise_for_status()
  File "/root/.virtualenvs/chaos/lib/python3.6/site-packages/requests/models.py", line 928, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/repos/chaosbot/Chaos/issues
Crashed in less than 60 seconds!
Rollback to commit 95a921fe117152173a28a7cb37d15477ec4abfc9
05-31 15:12 chaosbot     INFO     checking if I crashed before...
05-31 15:12 chaosbot     INFO     it looks like I did... posting on github...
05-31 15:12 github_api   DEBUG    requests remaining: inf, reset in: 0s, cooldown sleep: 0.00s
05-31 15:12 github_api   INFO     requesting POST to '/repos/chaosbot/Chaos/issues'
Traceback (most recent call last):
  File "chaos.py", line 116, in <module>
    main()
  File "chaos.py", line 49, in main
    check_for_prev_crash(api, log)
  File "chaos.py", line 109, in check_for_prev_crash
    gh.issues.create_issue(api, settings.URN, title, body, labels)
  File "/root/workspace/Chaos/github_api/issues.py", line 60, in create_issue
    resp = api("post", path, json=data)
  File "/root/workspace/Chaos/github_api/__init__.py", line 93, in __call__
    resp.raise_for_status()
  File "/root/.virtualenvs/chaos/lib/python3.6/site-packages/requests/models.py", line 928, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/repos/chaosbot/Chaos/issues
Crashed in less than 60 seconds!
Rollback to commit 39b78677665ff85245586740ad0312fbe849727e
05-31 15:13 chaosbot     INFO     checking if I crashed before...
05-31 15:13 chaosbot     INFO     it looks like I did... posting on github...
05-31 15:13 github_api   DEBUG    requests remaining: inf, reset in: 0s, cooldown sleep: 0.00s
05-31 15:13 github_api   INFO     requesting POST to '/repos/chaosbot/Chaos/issues'
Traceback (most recent call last):
  File "chaos.py", line 116, in <module>
    main()
  File "chaos.py", line 49, in main
    check_for_prev_crash(api, log)
  File "chaos.py", line 109, in check_for_prev_crash
    gh.issues.create_issue(api, settings.URN, title, body, labels)
  File "/root/workspace/Chaos/github_api/issues.py", line 60, in create_issue
    resp = api("post", path, json=data)
  File "/root/workspace/Chaos/github_api/__init__.py", line 93, in __call__
    resp.raise_for_status()
  File "/root/.virtualenvs/chaos/lib/python3.6/site-packages/requests/models.py", line 928, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/repos/chaosbot/Chaos/issues
Crashed in less than 60 seconds!
Rollback to commit 5d56e7cd092ae2b57c3a879c01c895c01825b683
05-31 15:21 chaosbot     INFO     checking if I crashed before...
05-31 15:21 chaosbot     INFO     starting up and entering event loop
05-31 15:21 stale_issues INFO     Checking for stale issues...
05-31 15:21 github_api   DEBUG    requests remaining: inf, reset in: 0s, cooldown sleep: 0.00s
05-31 15:21 github_api   INFO     requesting GET to '/repos/chaosbot/Chaos/issues'
05-31 15:21 stale_issues INFO     There are currently 30 open issues
05-31 15:21 stale_issues INFO     Issue 434 has not been updated in -251 seconds
05-31 15:21 stale_issues INFO     Issue 433 has not been updated in -665 seconds
05-31 15:21 stale_issues INFO     Issue 432 has not been updated in 3432 seconds
05-31 15:21 stale_issues INFO     Issue 431 has not been updated in -662 seconds
05-31 15:21 stale_issues INFO     Issue 430 has not been updated in -629 seconds
05-31 15:21 stale_issues INFO     Issue 429 has not been updated in 16923 seconds
05-31 15:21 stale_issues INFO     Issue 424 has not been updated in 33927 seconds
05-31 15:21 stale_issues INFO     Issue 423 has not been updated in -668 seconds
05-31 15:21 stale_issues INFO     Issue 422 has not been updated in 17942 seconds
05-31 15:21 stale_issues INFO     Issue 420 has not been updated in 33867 seconds
05-31 15:21 stale_issues INFO     Issue 414 has not been updated in 53035 seconds
05-31 15:21 stale_issues INFO     Issue 412 has not been updated in 3992 seconds
05-31 15:21 stale_issues INFO     Issue 409 has not been updated in 62445 seconds
05-31 15:21 stale_issues INFO     Issue 408 has not been updated in 57101 seconds
05-31 15:21 stale_issues INFO     Issue 407 has not been updated in 57558 seconds
05-31 15:21 stale_issues INFO     Issue 402 has not been updated in 72379 seconds
05-31 15:21 stale_issues INFO     Issue 401 has not been updated in 63022 seconds
05-31 15:21 stale_issues INFO     Issue 400 has not been updated in 27365 seconds
05-31 15:21 stale_issues INFO     Issue 398 has not been updated in 18072 seconds
05-31 15:21 stale_issues INFO     Issue 397 has not been updated in 57161 seconds
05-31 15:21 stale_issues INFO     Issue 391 has not been updated in 75946 seconds
05-31 15:21 stale_issues INFO     Issue 386 has not been updated in 40868 seconds
05-31 15:21 stale_issues INFO     Issue 381 has not been updated in 16848 seconds
05-31 15:21 stale_issues INFO     Issue 374 has not been updated in 2967 seconds
05-31 15:21 stale_issues INFO     Issue 365 has not been updated in 150328 seconds
05-31 15:21 stale_issues INFO     Issue 364 has not been updated in 157154 seconds
05-31 15:21 stale_issues INFO     Issue 353 has not been updated in 105183 seconds
05-31 15:21 stale_issues INFO     Issue 345 has not been updated in 220238 seconds
05-31 15:21 stale_issues INFO     Issue 310 has not been updated in 92924 seconds
05-31 15:21 stale_issues INFO     Issue 307 has not been updated in 39048 seconds
05-31 15:21 chaosbot     INFO     Setting description to A social coding experiment that updates its own code democratically.
05-31 15:21 github_api   DEBUG    requests remaining: 4990, reset in: 2498s, cooldown sleep: 0.01s
05-31 15:21 github_api   INFO     requesting PATCH to '/repos/chaosbot/Chaos'
05-31 15:22 chaosbot     INFO     checking if I crashed before...
05-31 15:22 chaosbot     INFO     starting up and entering event loop
05-31 15:22 stale_issues INFO     Checking for stale issues...
05-31 15:22 github_api   DEBUG    requests remaining: inf, reset in: 0s, cooldown sleep: 0.00s
05-31 15:22 github_api   INFO     requesting GET to '/repos/andrewda/Chaos/issues'
05-31 15:22 stale_issues INFO     There are currently 0 open issues
05-31 15:22 chaosbot     INFO     Setting description to A social coding experiment that updates its own code democratically.
05-31 15:22 github_api   DEBUG    requests remaining: 4989, reset in: 2395s, cooldown sleep: 0.01s
05-31 15:22 github_api   INFO     requesting PATCH to '/repos/andrewda/Chaos'
05-31 15:23 schedule     INFO     Running job Every 30 seconds do <lambda>() (last run: [never], next run: 2017-05-31 15:23:24)
05-31 15:23 pull_requests INFO     looking for PRs
05-31 15:23 github_api   DEBUG    requests remaining: 4988, reset in: 2369s, cooldown sleep: 0.01s
05-31 15:23 github_api   INFO     requesting GET to '/repos/andrewda/Chaos/stats/contributors'
05-31 15:23 github_api   DEBUG    requests remaining: 4987, reset in: 2360s, cooldown sleep: 0.01s
05-31 15:23 github_api   INFO     requesting GET to '/repos/andrewda/Chaos/stats/contributors'
05-31 15:23 pull_requests INFO     generated meritocracy: {'smittyvb', 'rhengles', 'muchzer', 'ad-m', 'mark-i-m', 'rudehn', 'plasmapower', 'eukaryote31', 'reddraggone9', 'hongaar', 'chaosbot', 'xyproto', 'amoffat', 'phil-r'}
05-31 15:23 github_api   DEBUG    requests remaining: 4986, reset in: 2356s, cooldown sleep: 0.01s
05-31 15:23 github_api   INFO     requesting GET to '/repos/andrewda/Chaos/pulls'
05-31 15:23 pull_requests INFO     Waiting 30 seconds until next scheduled PR polling event
05-31 15:24 schedule     INFO     Running job Every 30 seconds do <lambda>() (last run: 2017-05-31 15:23:40, next run: 2017-05-31 15:24:10)
05-31 15:24 pull_requests INFO     looking for PRs
05-31 15:24 pull_requests INFO     generated meritocracy: {'smittyvb', 'rhengles', 'muchzer', 'ad-m', 'mark-i-m', 'rudehn', 'plasmapower', 'eukaryote31', 'reddraggone9', 'hongaar', 'chaosbot', 'xyproto', 'amoffat', 'phil-r'}
05-31 15:24 github_api   DEBUG    requests remaining: 4985, reset in: 2323s, cooldown sleep: 0.01s
05-31 15:24 github_api   INFO     requesting GET to '/repos/andrewda/Chaos/pulls'
05-31 15:24 pull_requests INFO     Waiting 30 seconds until next scheduled PR polling event
05-31 15:24 schedule     INFO     Running job Every 30 seconds do <lambda>() (last run: 2017-05-31 15:24:13, next run: 2017-05-31 15:24:43)
05-31 15:24 pull_requests INFO     looking for PRs
05-31 15:24 pull_requests INFO     generated meritocracy: {'smittyvb', 'rhengles', 'muchzer', 'ad-m', 'mark-i-m', 'rudehn', 'plasmapower', 'eukaryote31', 'reddraggone9', 'hongaar', 'chaosbot', 'xyproto', 'amoffat', 'phil-r'}
05-31 15:24 github_api   DEBUG    requests remaining: 4984, reset in: 2290s, cooldown sleep: 0.01s
05-31 15:24 github_api   INFO     requesting GET to '/repos/andrewda/Chaos/pulls'
05-31 15:24 pull_requests INFO     Waiting 30 seconds until next scheduled PR polling event
05-31 15:34 schedule     INFO     Running job Every 30 seconds do <lambda>() (last run: 2017-05-31 15:24:46, next run: 2017-05-31 15:25:16)
05-31 15:34 pull_requests INFO     looking for PRs
05-31 15:34 pull_requests INFO     generated meritocracy: {'smittyvb', 'rhengles', 'muchzer', 'ad-m', 'mark-i-m', 'rudehn', 'plasmapower', 'eukaryote31', 'reddraggone9', 'hongaar', 'chaosbot', 'xyproto', 'amoffat', 'phil-r'}
05-31 15:34 github_api   DEBUG    requests remaining: 4983, reset in: 1717s, cooldown sleep: 0.00s
05-31 15:34 github_api   INFO     requesting GET to '/repos/andrewda/Chaos/pulls'
05-31 15:34 pull_requests INFO     Waiting 30 seconds until next scheduled PR polling event
05-31 15:34 schedule     INFO     Running job Every 600 seconds do <lambda>() (last run: [never], next run: 2017-05-31 15:32:54)
05-31 15:34 issue_commands INFO     looking for issue comments
05-31 15:34 github_api   DEBUG    requests remaining: 4982, reset in: 1714s, cooldown sleep: 0.00s
05-31 15:34 github_api   INFO     requesting GET to '/repos/andrewda/Chaos/issues/comments'
05-31 15:35 issue_commands INFO     Waiting 600 seconds until next scheduled Issue comment polling
05-31 15:35 schedule     INFO     Running job Every 30 seconds do <lambda>() (last run: 2017-05-31 15:34:19, next run: 2017-05-31 15:34:49)
05-31 15:35 pull_requests INFO     looking for PRs
05-31 15:35 pull_requests INFO     generated meritocracy: {'smittyvb', 'rhengles', 'muchzer', 'ad-m', 'mark-i-m', 'rudehn', 'plasmapower', 'eukaryote31', 'reddraggone9', 'hongaar', 'chaosbot', 'xyproto', 'amoffat', 'phil-r'}
05-31 15:35 github_api   DEBUG    requests remaining: 4981, reset in: 1629s, cooldown sleep: 0.00s
05-31 15:35 github_api   INFO     requesting GET to '/repos/andrewda/Chaos/pulls'
05-31 15:36 pull_requests INFO     Waiting 30 seconds until next scheduled PR polling event
05-31 15:36 schedule     INFO     Running job Every 30 seconds do <lambda>() (last run: 2017-05-31 15:36:26, next run: 2017-05-31 15:36:56)
05-31 15:36 pull_requests INFO     looking for PRs
05-31 15:36 pull_requests INFO     generated meritocracy: {'smittyvb', 'rhengles', 'muchzer', 'ad-m', 'mark-i-m', 'rudehn', 'plasmapower', 'eukaryote31', 'reddraggone9', 'hongaar', 'chaosbot', 'xyproto', 'amoffat', 'phil-r'}
05-31 15:36 github_api   DEBUG    requests remaining: 4980, reset in: 1556s, cooldown sleep: 0.00s
05-31 15:36 github_api   INFO     requesting GET to '/repos/andrewda/Chaos/pulls'
05-31 15:37 pull_requests INFO     Waiting 30 seconds until next scheduled PR polling event
06-01 05:50 chaosbot     INFO     checking if I crashed before...
06-01 05:50 chaosbot     INFO     starting up and entering event loop
06-01 05:50 stale_issues INFO     Checking for stale issues...
06-01 05:50 github_api   DEBUG    requests remaining: inf, reset in: 0s, cooldown sleep: 0.00s
06-01 05:50 github_api   INFO     requesting GET to '/repos/andrewda/Chaos/issues'
06-01 05:50 stale_issues INFO     There are currently 2 open issues
Traceback (most recent call last):
  File "chaos.py", line 118, in <module>
    main()
  File "chaos.py", line 59, in main
    cron.schedule_jobs(api)
  File "/root/workspace/Chaos/cron/__init__.py", line 19, in schedule_jobs
    poll_issue_close_stale(api)
  File "/root/workspace/Chaos/cron/poll_issue_close_stale.py", line 25, in poll_issue_close_stale
    number = issue["number"]
TypeError: list indices must be integers or slices, not str
Crashed in less than 60 seconds!
Rollback to commit 06596d92e4309ed7da6d992a328f5bff6c06a064
Checking out files:  27% (27/100)   
Checking out files:  28% (28/100)   
Checking out files:  29% (29/100)   
Checking out files:  30% (30/100)   
Checking out files:  31% (31/100)   
Checking out files:  32% (32/100)   
Checking out files:  33% (33/100)   
Checking out files:  34% (34/100)   
Checking out files:  35% (35/100)   
Checking out files:  36% (36/100)   
Checking out files:  37% (37/100)   
Checking out files:  38% (38/100)   
Checking out files:  39% (39/100)   
Checking out files:  40% (40/100)   
Checking out files:  41% (41/100)   
Checking out files:  42% (42/100)   
Checking out files:  43% (43/100)   
Checking out files:  44% (44/100)   
Checking out files:  45% (45/100)   
Checking out files:  46% (46/100)   
Checking out files:  47% (47/100)   
Checking out files:  48% (48/100)   
Checking out files:  49% (49/100)   
Checking out files:  50% (50/100)   
Checking out files:  51% (51/100)   
Checking out files:  52% (52/100)   
Checking out files:  53% (53/100)   
Checking out files:  54% (54/100)   
Checking out files:  55% (55/100)   
Checking out files:  56% (56/100)   
Checking out files:  57% (57/100)   
Checking out files:  58% (58/100)   
Checking out files:  59% (59/100)   
Checking out files:  60% (60/100)   
Checking out files:  61% (61/100)   
Checking out files:  62% (62/100)   
Checking out files:  63% (63/100)   
Checking out files:  64% (64/100)   
Checking out files:  65% (65/100)   
Checking out files:  66% (66/100)   
Checking out files:  67% (67/100)   
Checking out files:  68% (68/100)   
Checking out files:  69% (69/100)   
Checking out files:  70% (70/100)   
Checking out files:  71% (71/100)   
Checking out files:  72% (72/100)   
Checking out files:  73% (73/100)   
Checking out files:  74% (74/100)   
Checking out files:  75% (75/100)   
Checking out files:  76% (76/100)   
Checking out files:  77% (77/100)   
Checking out files:  78% (78/100)   
Checking out files:  79% (79/100)   
Checking out files:  80% (80/100)   
Checking out files:  81% (81/100)   
Checking out files:  82% (82/100)   
Checking out files:  83% (83/100)   
Checking out files:  84% (84/100)   
Checking out files:  85% (85/100)   
Checking out files:  86% (86/100)   
Checking out files:  87% (87/100)   
Checking out files:  88% (88/100)   
Checking out files:  89% (89/100)   
Checking out files:  90% (90/100)   
Checking out files:  91% (91/100)   
Checking out files:  92% (92/100)   
Checking out files:  93% (93/100)   
Checking out files:  94% (94/100)   
Checking out files:  95% (95/100)   
Checking out files:  96% (96/100)   
Checking out files:  97% (97/100)   
Checking out files:  98% (98/100)   
Checking out files:  99% (99/100)   
Checking out files: 100% (100/100)   
Checking out files: 100% (100/100), done.
06-01 05:51 chaosbot     INFO     checking if I crashed before...
06-01 05:51 chaosbot     INFO     it looks like I did... posting on github...

```

**Comment by andrewda** [comment]
guess my local instance posted here for some reason 😬
