### ISSUE TITLE
Public Apology

### ISSUE THREAD

**Issue by Swizz** [Chaosthebot/Chaos#458]
Fellows, I wrote theses lines to genuinely apologize.

Today, I broke our lovely bots with a naive comit 651c90a.
Today, I published a PR without any testing.
Today, I based all my stuffs on myself confidence.
Today, I failed.

So, Today,  I apologize.

**Comment by Swizz** [comment]
Proof of my guilt
```
06-01 12:12 chaosbot     INFO     Ensure creation of issue/PR labels
06-01 12:12 github_api   DEBUG    requests remaining: 2866, reset in: 1934s, cooldown sleep: 0.03s
06-01 12:12 github_api   INFO     requesting POST to '/repos/chaosbot/Chaos/labels'
06-01 12:12 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): api.github.com
06-01 12:12 urllib3.connectionpool DEBUG    https://api.github.com:443 "POST /repos/chaosbot/Chaos/labels HTTP/1.1" 422 186
Traceback (most recent call last):
  File "chaos.py", line 120, in <module>
    main()
  File "chaos.py", line 66, in main
    github_api.repos.create_label(api, settings.URN, label, color)
  File "/root/workspace/Chaos/github_api/repos.py", line 46, in create_label
    return api("post", "/repos/{urn}/labels".format(urn=urn), json=data)
  File "/root/workspace/Chaos/github_api/__init__.py", line 93, in __call__
    resp.raise_for_status()
  File "/root/.virtualenvs/chaos/lib/python3.6/site-packages/requests/models.py", line 929, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.github.com/repos/chaosbot/Chaos/labels
```

**Comment by rudehn** [comment]
You're certainly not the first one

**Comment by Swizz** [comment]
I didn't noticed the  `resp.raise_for_status()`, so in my mind silent error, will not throw anything ^^'

We learn by our mistakes o/
