### ISSUE TITLE
chaosbot down - database PR

### ISSUE THREAD

**Issue by amoffat** [Chaosthebot/Chaos#490]
current head yields this on startup:

```
Traceback (most recent call last):
  File "chaos.py", line 145, in <module>
    main()
  File "chaos.py", line 95, in main
    schedule.run_pending()
  File "/root/.virtualenvs/chaos/lib/python3.6/site-packages/schedule/__init__.py", line 462, in run_pending
    default_scheduler.run_pending()
  File "/root/.virtualenvs/chaos/lib/python3.6/site-packages/schedule/__init__.py", line 75, in run_pending
    self._run_job(job)
  File "/root/.virtualenvs/chaos/lib/python3.6/site-packages/schedule/__init__.py", line 129, in _run_job
    ret = job.run()
  File "/root/.virtualenvs/chaos/lib/python3.6/site-packages/schedule/__init__.py", line 377, in run
    ret = self.job_func()
  File "/root/workspace/Chaos/cron/__init__.py", line 11, in <lambda>
    lambda: poll_pull_requests(api))
  File "/root/workspace/Chaos/cron/poll_pull_requests.py", line 19, in poll_pull_requests
    db = DB.get_instance()
  File "/root/workspace/Chaos/lib/db.py", line 18, in get_instance
    DB.instance = DB(settings.DB_ADAPTER, settings.DB_CONFIG)
  File "/root/workspace/Chaos/lib/db.py", line 31, in __init__
    self.adapter = self.create_adapter(adapter_name, config)
  File "/root/workspace/Chaos/lib/db.py", line 27, in create_adapter
    return getattr(module_instance, class_name)(config)
TypeError: __new__() missing 2 required positional arguments: 'bases' and 'namespace'
Exception ignored in: <bound method DB.__del__ of <lib.db.DB object at 0x7fa92a8d7320>>
Traceback (most recent call last):
  File "/root/workspace/Chaos/lib/db.py", line 35, in __del__
    self.adapter.disconnect()
AttributeError: 'DB' object has no attribute 'adapter'
```

The real error here is `TypeError: __new__() missing 2 required positional arguments: 'bases' and 'namespace'`  Will merge a manual PR fixing this.

**Comment by rudehn** [comment]
I'm going to rewrite the db stuff. Should make this a lot smoother

**Comment by PlasmaPower** [comment]
@rudehn thanks! The DB seems to have been causing a lot of trouble. The meritocracy mentioned code currently uses the DB, mind rewriting that too?

**Comment by rudehn** [comment]
Yeah I'll get something up tomorrow.

**Comment by amoffat** [comment]
hotfixes

https://github.com/chaosbot/Chaos/commit/8637b39d66303c19c70552fa4b593884368dde9b
https://github.com/chaosbot/Chaos/commit/626de9e3a72c0a97da5b1d295c0d2e79db4c184e
